# docker-compose.yml
  services:
    dashboard:
      image:  nikhil7458/ecommerce-dashboard:1.0
      container_name: ecommerce-dashboard
      ports:
        - "80:80"
      environment:
        USER_HOST: 10.0.0.62
        PROFILE_HOST: 10.0.24.229
        PRODUCT_HOST: localhost
        CART_HOST: 10.0.25.142
        ORDER_HOST: localhost
        PAYMENT_HOST: localhost
      restart: unless-stopped